### ISSUE TITLE
ESP32 and ESP32-S3 example

### ISSUE THREAD

**Issue by georgik** [JurajSadel/esp32c3-no-std-async-mqtt-demo#7]
It's very nice example for ESP32-C3. 

Please, could you provide also the example for other most common ESP32 chips like plain old ESP32 and ESP32-S3 which are popular in some ePaper based boards?

**Comment by JurajSadel** [comment]
Thank you for the suggestion.
Created https://github.com/JurajSadel/esp32-no-std-async-mqtt-demo and https://github.com/JurajSadel/esp32s3-no-std-async-mqtt-demo
